export const OFFICIAL_BANOQABIL_COURSES = [
  "Digital Journalism",
  "Cyber Security Fundamentals",
  "Game Development with Blender",
  "Game Development with Unity",
  "SQA & Test Engineering",
  "Mobile Application Development with Flutter",
  "Digital Forensics and Ethical Hacking",
  "Web Development with AI",
  "Frontend Development with React & Next.JS",
  "MERN Stack Development",
  "Generative AI",
  "No-Code Development",
  "Prompt Engineering for Beginners",
  "AI for Everyone",
  "Digital Entrepreneurship for Women",
  "Daraz Ecosystem",
  "Computer Information and Technology",
  "Social Media Management",
  "Facebook & YouTube Automations",
  "UI-UX Design with Figma",
  "Data Analytics & BI",
  "Python Programming",
  "DevOps Foundations",
  "Amazon Virtual Assistant",
  "Content Writing",
  "Digital Marketing",
  "E-Commerce Development",
  "Graphic Designing Essentials",
  "Video Editing & Animations"
];
